### PR TITLE
Update BuildManager.cpp

### PR DESCRIPTION
**Pull request by Romz24**
I found that this file contains all the objects that are not used in the samp.

### CODE REVIEW

**Comment by Crayder** [comment]
I don't think this should be removed, some people may use custom IDE files. For example... I tested the Batman conversion mod which just adds to the current IDE files. Someone could easily use ColAndreas with a mod like that.

**Comment by Romz24** [comment]
In that case, it would be nice if you add the ability to exclude some ide files in WizardApp, what do you think about this?

**Comment by Crayder** [comment]
That I believe would be useful. We could add an "Advanced" button that lists all of the IDE's in the folder and allows selection and deselection of them.

**Comment by Romz24** [comment]
If you do this, it will be great and very useful.

**Comment by Pottus** [comment]
old

**Pull request closed without merging**
